# Generated by Django 5.2.4 on 2026-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("open", "Открыт"), ("closed", "Закрыт")],
                default="open",
                max_length=10,
                verbose_name="Статус",
            ),
        ),
    ]
